---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  become: true
  vars:
    # - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy
  environment:
    ENVIRONMENT: "{{ ENVIRONMENT }}"
    TYPEORM_CONNECTION: "{{ TYPEORM_CONNECTION }}"
    TYPEORM_ENTITIES: "{{ TYPEORM_ENTITIES }}"
    TYPEORM_HOST: "{{ TYPEORM_HOST }}"
    TYPEORM_PORT: "{{ TYPEORM_PORT }}"
    TYPEORM_USERNAME: "{{ TYPEORM_USERNAME }}"
    TYPEORM_PASSWORD: "{{ TYPEORM_PASSWORD }}"
    TYPEORM_DATABASE: "{{ TYPEORM_DATABASE }}"

